baseURL = 'https://akitoyamashita.github.io/'
locale = 'ja-jp'
defaultContentLanguage = 'ja'
title = "AkitoYamashita.github.io"

enableGitInfo = true

[markup.goldmark.renderer]
unsafe = true

# [[module.mounts]]
# source = "content"
# target = "content"

[[module.mounts]]
source = "../markdown"
target = "content"

ignoreFiles = [
    # 'markdown/ignore_directory/',
    '^draft/'
]
