baseURL = 'https://example.org/'
locale = 'en-us'
title = "AkitoYamashita"

enableGitInfo = true

[[module.mounts]]
source = "content"
target = "content"

[[module.mounts]]
source = "../markdown/note"
target = "content/note"
