AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  SYSTEM:
    Type: String
  ENV:
    Type: String
    AllowedValues: 
      - PRD
      - STG
      - DEV
  S3BucketName:
    Type: String
    Default: s3-com-prd-work-abcdefghijklmnopqrstuvwxyz

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${S3BucketName}
      PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
      WebsiteConfiguration: 
        IndexDocument: index.html
        ErrorDocument: error.html
      Tags:
        - Key: SYSTEM
          Value: !Sub ${SYSTEM}
        - Key: ENV
          Value: !Sub ${ENV}
        - Key: STACK_NAME
          Value: !Ref AWS::StackName
      
  S3BucketPolicy:
    DependsOn: S3Bucket
    Type: "AWS::S3::BucketPolicy"
    Properties:
      PolicyDocument:
        Statement:
          - Action:
            - "s3:GetObject"
            Effect: "Allow"
            Resource: !Sub "arn:aws:s3:::${S3BucketName}/*"
            Principal: "*"
      Bucket: !Ref S3Bucket

Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
