name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          mkdir artifact_dir
          date > artifact_dir/index.html

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: npm
        run: npm ci

      - name: build
        run: ./node_modules/vuepress/bin/vuepress.js build src

      - uses: actions/upload-artifact@v3
        with:
          name: my_site
          path: artifact_dir

      - uses: actions/upload-pages-artifact@v1
        with:
          path: artifact_dir
  deploy:
    needs: build
    runs-on: ubuntu-latest 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
